---
- name: add repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886

- name: add repo
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"

- name: automatically select the Oracle License
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: install java
  apt: name=oracle-java8-installer state=present update_cache=yes force=yes

- name: make java 8 default
  apt: name=oracle-java8-set-default state=present
  when: isDefault

