---
- name: Add Elasticsearch apt key.
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Add Elasticsearch repository.
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.7/debian stable main"

- name: install Elasticsearch.
  apt: pkg=elasticsearch state=present

- name: Configure Elasticsearch.
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml regexp='{{ item.regexp }}' line='{{ item.line }}' state=present"
  with_items:
    - { regexp: '^script\.disable_dynamic', line: 'script.disable_dynamic: true' }
    - { regexp: 'network\.host', line: 'network.host: localhost' }
  notify: restart elasticsearch

- name: start elasticsearch
  service: name=elasticsearch state=started enabled=yes

